# Use an official Python runtime as a parent image
FROM python:3.9-slim
# Set the working directory in the container
WORKDIR /app
# Copy the current directory contents into the container at /app
COPY . .
# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt
# Make port 6000 available to the world outside this container
EXPOSE 6000
# Define environment variable
ENV PORT=6000

# Run app.py when the container launches
CMD ["sh", "-c", "python app.py --port $PORT"]

# End of File
