# TODO: Define the Workflow Name
name: Frontend/Backend CI/CD Pipline

# TODO: Define triggers for the workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # TODO: Define a job for building and testing the frontend
  frontend:
    runs-on: ubuntu-latest
    steps:
       # TODO: Checkout code
      - uses: actions/checkout@v2
       
      # TODO: Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      # TODO: Install dependencies
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install 

        
      # TODO: Run tests
      # - name: Run tests
      #   working-directory: ./frontend
      #   run: npm run test 
        
      # TODO: Build the React app
      - name: Build the React App
        working-directory: ./frontend
        run: npm run build

  # TODO: Define a job for building and testing the backend
  backend:
    runs-on: ubuntu-latest
    steps:
      # TODO: Checkout code
      # TODO: Setup Python
      # TODO: Install dependencies
      # TODO: Run tests
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        # Add command to install dependencies
        run: |
          echo "Installing dependencies..."
          pip install -r ./backend/requirements.txt  # Install project dependencies

  # TODO: Define a job for building and pushing Docker images
  docker:
    # Run this job only when 'frontend' & 'backend' stages are sucessfully completed
    needs: [frontend,backend]
    runs-on: ubuntu-latest
    steps:
      # TODO: Checkout code
      - uses: actions/checkout@v2
      # TODO: Setup Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Set up Docker Hub credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # TODO: Build frontend Docker image
      - name: Build Docker Image
        run: |
          docker build -t tataothow101/frontend:${{ github.sha }} ./frontend

      - name: Push Docker Image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push tataothow101/frontend:${{ github.sha }}
      # - name: Build frontend Docker image
      #   run: |
      #     docker build  -t tataothow101/frontend:${{ github.sha }} ./frontend
      # # TODO: Push images to Docker Hub (if on main branch)
      # - name: Push frontend Docker image
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     docker push tataothow101/frontend:${{ github.sha }}
     
      



      # TODO: Build backend Docker image
      - name: Build backend Docker image
        run: |
          docker build -t tataothow101/backend:${{ github.sha }} ./backend
      # TODO: Push images to Docker Hub (if on main branch)
      - name: Push backend Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push tataothow101/backend:${{ github.sha }}

  # OPTIONAL: Define a deployment job (if applicable)
  # deploy:
  #   needs: docker
  #   runs-on: ubuntu-latest
    # steps:
      # TODO: Add deployment steps
