# TODO: Define the Workflow Name
name: Frontend/Backend CI/CD Pipline

# TODO: Define triggers for the workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # TODO: Define a job for building and testing the frontend
  frontend:
    runs-on: ubuntu-latest
    steps:
       # TODO: Checkout code
      - uses: actions/checkout@v2
       
      # TODO: Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      # TODO: Install dependencies
      - name: Install dependencies
        run: npm install
      # TODO: Run tests
      - name: Run tests
        run: npm run test
        
      # TODO: Build the React app
      - name: Build the React App
        run: npm run build

  # TODO: Define a job for building and testing the backend
  backend:
    runs-on: ubuntu-latest
    steps:
      # TODO: Checkout code
      # TODO: Setup Python
      # TODO: Install dependencies
      # TODO: Run tests
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        # Add command to install dependencies
        run: |
          echo "Installing dependencies..."
          pip install -r ./backend/requirements.txt  # Install project dependencies

  # TODO: Define a job for building and pushing Docker images
  # docker:
    # Run this job only when 'frontend' & 'backend' stages are sucessfully completed
    # needs:
    # runs-on: ubuntu-latest
    # steps:
      # TODO: Checkout code
      # TODO: Setup Docker
      # TODO: Build frontend Docker image
      # TODO: Build backend Docker image
      # TODO: Push images to Docker Hub (if on main branch)

  # OPTIONAL: Define a deployment job (if applicable)
  # deploy:
  #   needs: docker
  #   runs-on: ubuntu-latest
    # steps:
      # TODO: Add deployment steps
